### ISSUE TITLE
LDIF template concept is broken

### ISSUE THREAD

**Issue by AlbanBedel** [nextcloud/ldap_write_support#145]
The LDIF template may produce invalid LDIF as it just paste the provided values as is without any regard for the LDIF syntax. This prevent using strong passwords and allow LDAP injection.

Looking at RFC2849 the current template concept expect that all values are SAFE-STRING (see page 4 of the RFC). Beside space and new lines this exclude any value that contains a colon or less-than. However LDIF doesn't support traditional escaping, instead the value has to be encoded in base64. For this the attribute name has to be followed by 2 colon instead of just one, like this:
```
userPassword:: e1BCS0RGMl9TSE....
```

**Comment by AlbanBedel** [comment]
Upon further inspection of the code it is not as bad as I previously thought. The generated LDIF is not passed as is to the server. It is split in lines and then in key/value pairs that are passed to ldap_add() which in turn can do the base64 encoding when needed. This "only" leave the potential LDAP injection.

**Comment by susnux** [comment]
fixed with #146
