### ISSUE TITLE
Does it's works with Active Directory ?

### ISSUE THREAD

**Issue by guidtz** [nextcloud/ldap_write_support#153]
Hello, I'll try ldap_write_support with active directory but It seems not to work.

I have errors : 
```
ldap_mod_replace(): Modify: Constraint violation
```
My template : 
```
dn: CN={UID},CN=Users,{BASE}
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
sAMAccountName: {UID}
displayName: {UID}
cn: {UID}
sn: {UID}
userPassword: {PWD}
```

**Comment by blizzz** [comment]
I believe I had some successful tests against Samab4, which is compatible to  a good degree. "Constraint violation" means simply that the LDAP server is not satisfied with the record data it got. Check out the objectclass definitions, and ensure that all required values are set.

**Comment by guidtz** [comment]
@blizzz that reasures me but I'll do to continue my testing :). Do you have a copy of you're configuration with Samba 4 ?

**Comment by andrewborell** [comment]
I can confirm this worked for me with SAMBA 4 using the following:   
dn: cn={UID},{BASE}
objectClass: inetOrgPerson
samaccountname: {UID}
uid: {UID}
displayName: {UID}
cn: {UID}
sn: {UID}
userPassword: {PWD}
