### ISSUE TITLE
NC 20 compat

### ISSUE THREAD

**Issue by vivacarvajalito** [nextcloud/ldap_write_support#220]
Hello, this error broke the app in NC 20.
```
OCP\AppFramework\QueryException: Could not resolve LDAPUserPluginManager! Class LDAPUserPluginManager does not exist
```

**Comment by blizzz** [comment]
It has not been release to 20 yet.

**Comment by pedro-nonfree** [comment]
I am surprised by this bug, ldap_write_support is an official plugin from nextcloud. Current download button page in nextcloud points to 20.1 version [1], it's true that I forced a little bit the upgrade on my server. But for me was totally unexpected to find this plugin not available yet for 20.x

In my opinion, this is an important plugin, so I don't know why nextcloud already anounced 20.x without waiting this plugin to be adapted.

[1] https://nextcloud.com/install/#instructions-server

**Comment by blizzz** [comment]
> In my opinion, this is an important plugin, so I don't know why nextcloud already anounced 20.x without waiting this plugin to be adapted.

Thank you for these words. However it is one of many apps and although i would have loved to release it earlier, I did not manage to for various reasons. Fortunately it is all open source ;)

Aynway, it is out now.
