### ISSUE TITLE
last nginx conf messed up the LDAP app

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/ldap_write_support#323]
The config from the [latest documentation](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) messed up the LDAP app. I had to use the config from [the NC19 docs](https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html).

I'm not the only one : https://help.nextcloud.com/t/ldap-configuration-on-fresh-install-just-hangs-nothing-in-error-log/102636

**Comment by susnux** [comment]
I am also using NGinx with the latest config, can not confirm this issue.
Please reopen if you encounter this issue again and provide more information what is not working, error logs etc.
