### ISSUE TITLE
ldap_write_support disabled on Nextcloud 21.0.2

### ISSUE THREAD

**Issue by guymass** [nextcloud/ldap_write_support#339]
Hi, I have lost my connection to ldap server after the recent upgrade, now ldap_write_support is not compatible with the new 21.0.2 version. Can we please have a fix for that? My cloud is basically now disabled because of this and I cannot even login with the native admin user nor can I downgrade, please this would really help at least to know someone here knows about it.
Much thanks for all the great efforts done on this.

Best Regards,

**Comment by blizzz** [comment]
it was not this app responsible for it. When the LDAP connection does not work, Nextcloud refuses to work as it is a critical component.
