### ISSUE TITLE
Is it possible configuration from CLI?

### ISSUE THREAD

**Issue by alexeysmovzh** [nextcloud/ldap_write_support#346]
Hello, 
thank you for your work! This module is very useful!

In our infrastructure we use infrastructure as code approach. For configuring nextcloud and its modules we use Puppet. And I want to automate ldap_write_support configuration process as well. But after some research I didn't find any recipe how to configure this module in any way instead of from Web UI.

Is it possible to configure ldap_write_support from CLI, configuration file or some other way that can be automated with configuration management software?

**Comment by blizzz** [comment]
Through generic occ config commands. If you have a working configuration, you can get it through `php occ config:list ldap_write_support`. Check out ` php occ config:import` or ` php occ config:app:set` for importing/setting values.

As this seems to be a setup issue I would like to ask you to follow up, if necessary, in the forums: https://help.nextcloud.com
