### ISSUE TITLE
Replace drone with github actions 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/ldap_write_support#354]
Please migrate your drone usage to github actions

**Comment by blizzz** [comment]
for which reason?

**Comment by nickvergessen** [comment]
To reduce the load on our server :P 

But well you can also decide to not do it. I just autocreated the issues in all repos which use it.

**Comment by blizzz** [comment]
Here applies what Gottfried August Bürger said: the test travel fast

Will close thus.
