### ISSUE TITLE
Email address changed for {userName}

### ISSUE THREAD

**Issue by moatazrabeea** [nextcloud/ldap_write_support#360]
I have nextcloud 21 installation I use Ldap Server
one of from Ldap Server users received this mail
Your email address on http://ServerIP / was changed by an administrator.by the way I am as administrator didn’t change nothing in this user settings. and the administrator can't list ldap users to edit in them also it sends my server IP instead of domain name it is so weired and confusing. I changed one of nextcloud users email created by nextcloud admin the mail is sent  Your email address on http://DomainName / was changed so how to know the cause of the mail

Server configuration

Operating system:

ubutnu 18.04

Web server:

Apache

Database:

Postgresql 

PHP version:

7.3.27

**Comment by come-nc** [comment]
Hello, sorry about the lack of answer, is this still happening with newer version?
I’m not a 100% sure what the issue also, the IP instead of domain name?
Or the unexpected email, but that’s impossible to debug with reproduction step.

Closing, please re-open if there is new information.
