### ISSUE TITLE
Update/Release for 23 & 24

### ISSUE THREAD

**Issue by pabsta1** [nextcloud/ldap_write_support#425]
The title says it all.

**Comment by pedro-nonfree** [comment]
Looks like we are having the same issue as #220 again

I suggest changing the title to *NC 23 Compat*

plugin still does not work for nextcloud v23 according to https://apps.nextcloud.com/apps/ldap_write_support

**Comment by politas** [comment]
This is the only thing holding me back from upgrading to Nextcloud 23

**Comment by francofischer** [comment]
> This is the only thing holding me back from upgrading to Nextcloud 23

We are using in NC 23 without any problem...

**Comment by pedro-nonfree** [comment]
thanks @francofischer , so you forced the installation?

how much time you have been running it in NC 23?

if it works fine in NC 23, then it would be time to just do the new release so you don't have to force the installation because it already works

**Comment by francofischer** [comment]
> thanks @francofischer , so you forced the installation?
> 
> how much time you have been running it in NC 23?
> 
> if it works fine in NC 23, then it would be time to just do the new release so you don't have to force the installation because it already works

Yes, we force the installation. 
We have about 1 month of a fresh installation of nextcloud. We are using freeIPA as LDAP server.

**Comment by politas** [comment]
It would still be much better if we could actually get the app updated to officially work with more recent versions.

**Comment by blizzz** [comment]
24 is now available as v1.6.0

**Comment by blizzz** [comment]
23 now as well as 1.5.0
