### ISSUE TITLE
Error: ldap_mod_replace(): Modify: Naming violation at /data/nextcloud/apps/ldap_write_support/lib/LDAPUserManager.php#130

### ISSUE THREAD

**Issue by saschabrockel** [nextcloud/ldap_write_support#459]
Hey there. Users cannot change their username. It ends up in the following error. The Nextcloud version is: [Nextcloud Hub II] (23.0.2)

`Error: ldap_mod_replace(): Modify: Naming violation at /data/nextcloud/apps/ldap_write_support/lib/LDAPUserManager.php#130<<closure>>OC\Log\ErrorHandler::onError(2, "ldap_mod_re ... n", "/data/nextc ... p", 130, { uid: "2ed8 ... "})/data/nextcloud/apps/ldap_write_support/lib/LDAPUserManager.php - line 130:ldap_mod_replace(null, "cn=chakir k ... e", { cn: "Chakira"})/data/nextcloud/apps/user_ldap/lib/UserPluginManager.php - line 173:OCA\LdapWriteSupport\LDAPUserManager->setDisplayName("2ed8d5d0-38 ... c", "Chakira")/data/nextcloud/apps/user_ldap/lib/User_LDAP.php - line 507:OCA\User_LDAP\UserPluginManager->setDisplayName("2ed8d5d0-38 ... c", "Chakira")<<closure>>OCA\User_LDAP\User_LDAP->setDisplayName("2ed8d5d0-38 ... c", "Chakira")/data/nextcloud/apps/user_ldap/lib/User_Proxy.php - line 81:call_user_func_array([ OCA\User_L ... "], [ "2ed8d5d0- ... "])/data/nextcloud/apps/user_ldap/lib/Proxy.php - line 171:OCA\User_LDAP\User_Proxy->walkBackends("2ed8d5d0-38 ... c", "setDisplayName", [ "2ed8d5d0- ... "])/data/nextcloud/apps/user_ldap/lib/User_Proxy.php - line 277:OCA\User_LDAP\Proxy->handleRequest("2ed8d5d0-38 ... c", "setDisplayName", [ "2ed8d5d0- ... "])/data/nextcloud/lib/private/User/User.php - line 161:OCA\User_LDAP\User_Proxy->setDisplayName("2ed8d5d0-38 ... c", "Chakira")/data/nextcloud/apps/settings/lib/Controller/UsersController.php - line 479:OC\User\User->setDisplayName("Chakira")/data/nextcloud/apps/settings/lib/Controller/UsersController.php - line 432:OCA\Settings\Controller\UsersController->saveUserSettings(OC\Accounts\Account {})/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Settings\Controller\UsersController->setUserSettings("v2-federated", "Chakira", null, "", "v2-local", "test@test.com", null, "", "v2-local", "", "v2-local", "", "v2-local")/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "setUserSettings")/data/nextcloud/lib/private/AppFramework/App.php - line 157:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "setUserSettings")/data/nextcloud/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main("OCA\\Settin ... r", "setUserSettings", OC\AppFramew ... {}, { username: ... "})/data/nextcloud/lib/base.php - line 1006:OC\Route\Router->match("/settings/u ... s")/data/nextcloud/index.php - line 36:OC::handleRequest()`

![image](https://user-images.githubusercontent.com/33376463/159142577-c0f39c41-6346-4ee2-9dab-600c4f5b8f33.png)

**Comment by susnux** [comment]
This happens if you set the `uid` as the `displayname` field in the `user_ldap` app settings. Is this the case for your setup?

**Comment by saschabrockel** [comment]
@susnux yes it is the case as you can see on the image. Still using it like this.

**Comment by susnux** [comment]
So what is the setting for your `user display name field`?
Because is that attribute is used in the DN of the entry `ldap_mod_replace` will fail with exactly the same error.
On m setup I use `displayName` as the display name field and `uid` for the dn, which works fine:
![image](https://user-images.githubusercontent.com/1855448/184675303-320922fd-414a-4f90-9f6f-552d908b2f49.png)

but if your DN is: `uid=...,BASE` and your display name field is also `uid` it will fail (if that is the case try to the display name field to `displayName` or `cn`).

**Comment by saschabrockel** [comment]
It worked! You were right. Thank you very much. They should write it down in the manual.
