### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by TERABITNET** [nextcloud/ldap_write_support#549]
We have deployed NEXTCLOUD using the AIO Docker image. NEXTCLOUD was integrated with Active Directory through LDAP. NEXTCLOUD was last updated in October 2022 and since then, we were not able to import new users from LDAP and the following error occurs "An error occurred during the request. Unable to proceed". Users imported before the update are normal. Please advise us on how to resolve this issue.

![Screenshot 2023-01-03 195724](https://user-images.githubusercontent.com/73290843/210352913-7487a0a0-400d-4df1-9987-d4f85fa2a933.png)

**Comment by theianspence** [comment]
How did you fix this?
