### ISSUE TITLE
Exception filling logs 

### ISSUE THREAD

**Issue by johnjaylward** [nextcloud/ldap_write_support#608]
My LDAP configuration is working (I can log in, and even update my password via LDAP).

However, this log message fills my logs up many time per minute:

[ldap-write error log.log](https://github.com/nextcloud/ldap_write_support/files/13552256/ldap-write.error.log.log)

Disabling the "Write support for LDAP" plugin stops the error messages.

**Comment by johnjaylward** [comment]
It seems that this plugin failing also caused failures in other plugins.

**Comment by susnux** [comment]
This error should only happen if you disable the `user_ldap` app.

**Comment by johnjaylward** [comment]
I had to restart the system. Something in the cache was breaking. The restart cleared the cache and the error stopped

**Comment by susnux** [comment]
Sounds like the PHP opcache was still hot, so the new class after an update was not loaded correctly.
