### ISSUE TITLE
fails to create user

### ISSUE THREAD

**Issue by mrizvic** [nextcloud/ldap_write_support#77]
This is what I get on LDAP server:

Oct 18 11:17:17 castor slapd[137]: conn=77671 fd=12 ACCEPT from IP=[censored]:39094 (IP=[::]:389)
Oct 18 11:17:17 castor slapd[137]: conn=77671 op=0 BIND dn="cn=admin,dc=censored,dc=censored" method=128
Oct 18 11:17:17 castor slapd[137]: conn=77671 op=0 BIND dn="cn=admin,dc=censored,dc=censored" mech=SIMPLE ssf=0
Oct 18 11:17:17 castor slapd[137]: conn=77671 op=0 RESULT tag=97 err=0 text=
Oct 18 11:17:17 castor slapd[137]: conn=77671 op=1 ADD dn="uid=testuser,dc=censored,dc=censored"
Oct 18 11:17:17 castor slapd[137]: conn=77671 op=1 RESULT tag=105 err=68 text=
Oct 18 11:17:17 castor slapd[137]: conn=77671 op=2 UNBIND
Oct 18 11:17:17 castor slapd[137]: conn=77671 fd=12 closed

Nextcloud user create GUI shows toast message saying: "An error occured during the request. Unable to proceed.
Bad request"

A little how-to documentation would be useful.

**Comment by blizzz** [comment]
>  Oct 18 11:17:17 castor slapd[137]: conn=77671 op=1 RESULT tag=105 err=68 text=

Error code 68 is: LDAP_ALREADY_EXISTS

> Add Request attempted to add an entry that already exists  [source](https://ldapwiki.com/wiki/LDAP_ALREADY_EXISTS)
