### ISSUE TITLE
User passwords are stored in plain text

### ISSUE THREAD

**Issue by klada** [nextcloud/ldap_write_support#86]
When initially creating a user the password is stored in plain-text in the LDAP directory. When changing the password for the first time a proper hash is stored, so this only affects new users created through this app.

This is a severe security issue. A proper password hash should be generated before when adding the user.

**Comment by blizzz** [comment]
The password change exop is being used (requires PHP >= 7.2). If the server does not handle it, configure ` password-hash` in your slapd.conf on the app server. The default should be SSHA however…

**Comment by klada** [comment]
@blizzz The issue is not with *changing* passwords. This works as expected and leads to a hashed password if the LDAP server is set up correctly.

The issue is that when *adding* a user, this app (`ldap_write_support`) generates LDIF data with the user's plaintext password in the `accountPassword` attribute. In most cases this is not what people want. If `setPassword` was actually called, everything would be fine, but `setPassword` is not called when adding users.

I think there are two options here to solve this:

1. Call `setPassword()` in `createUser()` after adding the user. This would probably be the easiest and most transparent approach, as it let's the server do the hasing.

2. Add support for a new placeholder in LDIF template (e.g. `SSHA_PWD`) when adding the user. The implementation in `buildNewEntry()` _could_ look like this (attention: completely untested!):
```php
// attention: salt needs to be 4 chars. this will probably not work
$salt = \OC::$server->getConfig()->getSystemValue('passwordsalt');
$ssha_pw = '{SSHA}'.base64_encode(sha1($password.$salt, TRUE).$salt);
$ldif = str_replace('{SSHA_PWD}', $ssha_pw, $ldif);
```

If you want I can come up with a PR for either option.

**Comment by blizzz** [comment]
@klada thanks for the clarification, and apologies for missing the core point. I'd very appreciate the PR! For systems still on 7.1 the first option is tricky, unless with a fallback. But since the second needs manual interference, the first approach is the more reliable one. Let's go for that.

**Comment by klada** [comment]
@blizzz I have prepared some changes and they are working for me.

There are some drawbacks though and I think you probably want to do some things differently:

- PHP 7.2+ is required (as you have mentioned) 
- I needed to rework `setPassword()` because `$this->ldapProvider->getLDAPConnection($uid)` /  `$this->getUserDN($uid)` are not working right after adding an LDAP user. My guess is that my workaround for this is not very elegant :smile: 
- I added a new private method for setting a password for a DN.
- ... and for sure I have overlooked something

**Comment by blizzz** [comment]
thanks, I will have a look and follow up in the PR!

**Comment by Samonitari** [comment]
Sorry to necro this!

Although it is (or can be considered a workaround), if the backend is OpenLDAP, @klada, you (or anybody having this issue) should load the ppolicy overlay and [enable backend-side cleartext hashing](https://github.com/osixia/docker-openldap/issues/208).
ARGON2 hash (nowadays the trendiest with the kids on the block) is missing from even the latest Apache Directory Studio, so I had to enable ppolicy's hashCleartext anyway.
BTW, server-side hashing before storing is a violation of x500/LDAP idiom of "no change of supplied data by the server", however "extended operation pw change" also is a violation of this (or some other) idiom, so...
